sudo: required
language: java
jdk: openjdk8
services: docker

install:
  # Install Nextflow
  - mkdir nextflow
  - cd nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s $PWD/nextflow /usr/local/bin/nextflow


# Install the pipeline
  - git clone --depth 1 https://github.com/biocorecrg/master_of_pores.git
  - cd master_of_pores/preprocessing
 
# Run the pipeline
script:
   - travis_wait 30 nextflow run preprocessing.nf -with-docker
