sudo: required
language: java
jdk: openjdk8
services: docker

install:
  # Install Nextflow
  - mkdir nextflow
  - cd nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s $PWD/nextflow /usr/local/bin/nextflow


# Run the pipeline
script:
   - travis_wait 30 nextflow run biocorecrg/master_of_pores -with-docker
